// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace TestFramework.Specs.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::Xunit.CollectionAttribute("Login")]
    [global::Xunit.TraitAttribute("Description", "Login")]
    // Reqnroll fixture lifecycle attributes converted to xUnit collection semantics.
    public partial class LoginFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "Login", null, global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        // xUnit does not have [OneTimeSetUp]; consider IAsyncLifetime for per-class setup.
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        // xUnit does not have [OneTimeTearDown]; consider IAsyncLifetime for per-class teardown.
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        // xUnit does not have direct [SetUp]; use constructor or IAsyncLifetime.InitializeAsync.
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        // xUnit does not have direct [TearDown]; use IAsyncLifetime.DisposeAsync.
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            // xUnit does not expose NUnit TestContext; having this as no-op for now.
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/Login.feature.ndjson", 4);
        }
        
        [global::Xunit.FactAttribute()]
        [global::Xunit.TraitAttribute("Description", "Successful login with valid credentials")]
        [global::Xunit.TraitAttribute("Category", "smoke")]
        [global::Xunit.TraitAttribute("Category", "ui")]
        public async global::System.Threading.Tasks.Task SuccessfulLoginWithValidCredentials()
        {
            string[] tagsOfScenario = new string[] {
                    "smoke",
                    "ui"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Successful login with valid credentials", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
            this.ScenarioInitialize(scenarioInfo, ruleInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                await testRunner.GivenAsync("the user opens the login page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                await testRunner.WhenAsync("the \"standard\" user logs in", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync("the inventory page should be displayed", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute()]
        [global::Xunit.TraitAttribute("Description", "Login fails with invalid credentials")]
        [global::Xunit.TraitAttribute("Category", "ui")]
        public async global::System.Threading.Tasks.Task LoginFailsWithInvalidCredentials()
        {
            string[] tagsOfScenario = new string[] {
                    "ui"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Login fails with invalid credentials", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
            this.ScenarioInitialize(scenarioInfo, ruleInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                await testRunner.GivenAsync("the user opens the login page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                await testRunner.WhenAsync("the \"invalid\" user logs in", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync("the login error message should be displayed", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion

